# Uncomment the following line to use OpenMP 2.0 features
#OMPFLAG = -DOMPVER2
# Uncomment the following line to use OpenMP 3.0 features
OMPFLAG = -DOMPVER2 -DOMPVER3

CC=~/openUH/bin/uhcc
CFLAGS = -O1 -lm -mp
LDFLAGS = -O0 -lm -mp
CPP = /usr/bin/cpp
LIBS =
