#!/bin/bash

grep "^PARALLEL TASK overhead" $1
grep "^MASTER TASK overhead" $1
grep "^MASTER TASK BUSY SLAVES overhead" $1
grep "^CONDITIONAL TASK overhead" $1
grep "^TASK WAIT overhead" $1
grep "^TASK BARRIER overhead" $1
grep "^NESTED TASK overhead" $1
grep "^NESTED MASTER TASK overhead" $1
grep "^BRANCH TASK TREE overhead" $1
grep "^LEAF TASK TREE overhead" $1
