#!/bin/csh
#
#  Sample Batch Script for a SGI Altix MPI job
#
#  Submit this script using the command: qsub aspcg.pbs
#
#  Use the "qstat" command to check the status of a job.
#
# The following are embedded QSUB options. The syntax is #PBS (the # does
# _not_ denote that the lines are commented out so do not remove).
#
# 
# Set maximum wallclock time to 30 minutes (hh:mm:ss)
#PBS -l walltime=00:30:00

# Set memory limit to 500 Mbytes
#PBS -l mem=1500mb

# Export all my environment variables to the job
#PBS -V
 
#set OpenMP threads
setenv OMP_NUM_THREADS 4
limit stacksize unlimited
#set stack size
setenv KMP_STACKSIZE 500M

#set MPI processes
#mpiprocs=1

# Request processors (openmp * mpi)
#PBS -l ncpus=4

# Queue name (see info about other queues in web documentation)
#PBS -q debug
#
# Charge job to project abc (recommended for users with multiple projects)
# [If project is invalid, a valid project will be automatically selected]
#PBS -A mya
# 
# Job name (default = name of script file)
#PBS -N epcc.omp
#
# Filename for standard output (default = <job_name>.o<job_id>)
#
# Filename for standard error (default = <job_name>.e<job_id>)
# 
# Send mail when the job begins and ends (optional)
#PBS -m e
#------------------------------
# End of embedded QSUB options

#set echo               # echo commands before execution; use for debugging
source /u/ac/liaoch/set.orc
/u/ac/liaoch/code/epcc/C/schedbench

