#!/bin/bash
# script to run epcc benchmark
# by Chunhua Liao
# University of Houston

# 1. set different thread number

for var in 1 2 3 4 5 6 7 8; do

  OMP_NUM_THREADS=$var
  export OMP_NUM_THREADS

  echo //////////////////////////
  echo set OpenMP threads to be  "$var"
  echo //////////////////////////

 # run 3 times for sync 
  for var2 in 1 2 3; do
    echo ////////////////////////
    echo run for the "$var2" time
    echo ///////////////////////
  date
  ./syncbench
  date
  done
done

#2. Run schedule benchmark using one thread number

  OMP_NUM_THREADS=4
  export OMP_NUM_THREADS

  echo //////////////////////////
  echo set OpenMP threads to be  "$OMP_NUM_THREADS"
  echo //////////////////////////

# run 3 times for schedule 
for var2 in 1 2 3; do
  echo ////////////////////////
  echo run for the "$var2" time
  echo ///////////////////////
date
  ./schedbench
date
done


#echo sequential version
#date
#time ./a.out.seq
#date
